export type Track = {
  id: string;
  title: string;
  artist: string;
  film: string;
  year: number;
  duration: number;
  videoId: string;
};

// Add a licensed/rightsholder-owned embeddable YouTube upload with one line.
// Do not add copyrighted tracks unless you have permission to use/embed them.
export const playlists: Record<string, Track[]> = {
  "Roja Radio": [
    {
      id: "naa-cheli-rojave",
      title: "Naa Cheli Rojave",
      artist: "S. P. Balasubrahmanyam, Sujatha Mohan",
      film: "Roja",
      year: 1992,
      duration: 292,
      videoId: "alm844msx6E",
    },
    {
      id: "paruvam-vanaga-roja",
      title: "Paruvam Vanaga",
      artist: "S. P. Balasubrahmanyam, Sujatha Mohan",
      film: "Roja",
      year: 1992,
      duration: 305,
      videoId: "AW5oraAriXc",
    },
    {
      id: "chinna-chinna-aasa-roja",
      title: "Chinni Chinni Aasa",
      artist: "Minmini",
      film: "Roja",
      year: 1992,
      duration: 295,
      videoId: "Wm5n8V4N5f0",
    },
    {
      id: "vinaraa-vinaraa-roja",
      title: "Vinaraa Vinaraa",
      artist: "Mano",
      film: "Roja",
      year: 1992,
      duration: 238,
      videoId: "OGRnRyRtT7Y",
    },
    {
      id: "kannanule-bombay",
      title: "Kannanule",
      artist: "Hariharan, Kavita Krishnamurthy",
      film: "Bombay",
      year: 1995,
      duration: 298,
      videoId: "p-1gysnu4MM",
    },
    {
      id: "urike-chilaka-bombay",
      title: "Urike Chilaka",
      artist: "Hariharan, K. S. Chithra",
      film: "Bombay",
      year: 1995,
      duration: 310,
      videoId: "4J5aQNqRu_A",
    },
    {
      id: "mustafa-mustafa-prema-desam",
      title: "Mustafa Mustafa",
      artist: "A. R. Rahman",
      film: "Prema Desam",
      year: 1996,
      duration: 360,
      videoId: "M791NkagYAM",
    },
    {
      id: "hello-doctor-prema-desam",
      title: "Hello Doctor",
      artist: "A. R. Rahman, Storms, Noel, Anupama",
      film: "Prema Desam",
      year: 1996,
      duration: 285,
      videoId: "wwXjRV4V-1U",
    },
    {
      id: "urvasi-urvasi-premikudu",
      title: "Urvasi Urvasi",
      artist: "A. R. Rahman, Suresh Peters",
      film: "Premikudu",
      year: 1994,
      duration: 340,
      videoId: "97uVDPOibYw",
    },
    {
      id: "mukkala-mukkabula-premikudu",
      title: "Mukkala Mukkabula",
      artist: "Mano, Swarnalatha",
      film: "Premikudu",
      year: 1994,
      duration: 320,
      videoId: "vaw0k8HiP9A",
    },
  ],
  "Dude OST": [
    {
      id: "oorum-blood-dude",
      title: "Oorum Blood",
      artist: "Sai Abhyankkar, Paal Dabba",
      film: "Dude",
      year: 2025,
      duration: 215,
      videoId: "4Bsc2uI_LsM",
    },
    {
      id: "singari-dude",
      title: "Singari",
      artist: "Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 230,
      videoId: "Ja7Yz0MPbwI",
    },
    {
      id: "nallaru-po-dude",
      title: "Nallaru Po",
      artist: "Tippu, Mohit Chauhan, Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 245,
      videoId: "-hZIVX0iv9w",
    },
    {
      id: "kannukulla-dude",
      title: "Kannukulla",
      artist: "Jonita Gandhi, Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 220,
      videoId: "sdajTOjARNg",
    },
    {
      id: "boom-boom-dude",
      title: "Boom Boom",
      artist: "Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 195,
      videoId: "jApMnFmv2ig",
    },
    {
      id: "oorum-blood-rage-rock",
      title: "Oorum Blood (Rage Rock OST)",
      artist: "Sai Abhyankkar",
      film: "Dude (Original Score)",
      year: 2025,
      duration: 160,
      videoId: "2expHBvjI0s",
    },
    {
      id: "dude-original-score-side-b",
      title: "Dude Original Score (Side B Jukebox)",
      artist: "Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 680,
      videoId: "f3i58ShlZjk",
    },
  ],
  "DC OST": [
    {
      id: "dc-raga-of-revenge",
      title: "Raga of Revenge",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 185,
      videoId: "El9lOzNyPb4",
    },
    {
      id: "dc-aint-nobody",
      title: "Ain't Nobody",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 205,
      videoId: "e2-yAj_wthU",
    },
    {
      id: "dc-bloody-band",
      title: "Bloody Band",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 210,
      videoId: "P15G5XA8si4",
    },
    {
      id: "dc-bum-baa-diga-diga",
      title: "Bum Baa Diga Diga",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 198,
      videoId: "X1twu3ztkPU",
    },
    {
      id: "dc-the-rose-instrumental",
      title: "The Rose (Instrumental OST)",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 175,
      videoId: "VCfrL292Gmk",
    },
    {
      id: "dc-unreleased-jukebox",
      title: "DC BGM Score & Bangers Jukebox",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 540,
      videoId: "JVbtS-Y_ckw",
    },
    {
      id: "the-dark-knight-main-theme",
      title: "The Dark Knight (Main Theme)",
      artist: "Hans Zimmer",
      film: "The Dark Knight (DC)",
      year: 2008,
      duration: 460,
      videoId: "iGx5a1ifSDs",
    },
    {
      id: "the-batman-theme",
      title: "The Batman (Main Theme)",
      artist: "Michael Giacchino",
      film: "The Batman (DC)",
      year: 2022,
      duration: 410,
      videoId: "Cwcinb2OxUo",
    },
    {
      id: "man-of-steel-flight",
      title: "Flight (Man of Steel OST)",
      artist: "Hans Zimmer",
      film: "Man of Steel (DC)",
      year: 2013,
      duration: 250,
      videoId: "w4OdIOGBW2Q",
    },
  ],
  "Cassette Evenings": [
    {
      id: "oh-priya-priya-geetanjali",
      title: "Oh Priya Priya",
      artist: "S. P. Balasubrahmanyam",
      film: "Geetanjali",
      year: 1989,
      duration: 308,
      videoId: "Q1a02C68ZXg",
    },
    {
      id: "aamani-paadave-geetanjali",
      title: "Aamani Paadave",
      artist: "K. S. Chithra",
      film: "Geetanjali",
      year: 1989,
      duration: 272,
      videoId: "vyH7ow2C4Zw",
    },
    {
      id: "oh-papa-laali-geetanjali",
      title: "Oh Papa Laali",
      artist: "Mano",
      film: "Geetanjali",
      year: 1989,
      duration: 290,
      videoId: "XK3gue1uR3w",
    },
    {
      id: "ee-manase-tholiprema",
      title: "Ee Manase Se Se",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Tholiprema",
      year: 1998,
      duration: 330,
      videoId: "zed5SZ2EiY0",
    },
    {
      id: "yemaindo-yemo-tholiprema",
      title: "Yemaindo Yemo Ee Vela",
      artist: "S. P. Balasubrahmanyam",
      film: "Tholiprema",
      year: 1998,
      duration: 290,
      videoId: "resKdlxjCbY",
    },
    {
      id: "telusa-manasa-criminal",
      title: "Telusa Manasa",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Criminal",
      year: 1994,
      duration: 295,
      videoId: "X206ZLAcKcI",
    },
    {
      id: "yeto-vellipoyindi-ninne-pelladata",
      title: "Yeto Vellipoyindi Manasu",
      artist: "Rajesh Krishnan, K. S. Chithra",
      film: "Ninne Pelladata",
      year: 1996,
      duration: 280,
      videoId: "FvcoRTJK_J8",
    },
    {
      id: "priya-priyathama-killer",
      title: "Priya Priyathama",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Killer",
      year: 1992,
      duration: 312,
      videoId: "Cc-0Tlg3SX8",
    },
    {
      id: "priyatama-naa-hrudayama-prema",
      title: "Priyatama Naa Hrudayama",
      artist: "S. P. Balasubrahmanyam",
      film: "Prema",
      year: 1989,
      duration: 315,
      videoId: "JSKSjPrnXU4",
    },
    {
      id: "kannula-basalu-prema-katha",
      title: "Kannula Baasalu",
      artist: "S. P. Balasubrahmanyam",
      film: "Prema Katha",
      year: 1999,
      duration: 275,
      videoId: "IGHHlJiv1ns",
    },
    {
      id: "chilaka-ye-thodu-leka-subhalagnam",
      title: "Chilaka Ye Thodu Leka",
      artist: "S. P. Balasubrahmanyam",
      film: "Subhalagnam",
      year: 1994,
      duration: 285,
      videoId: "LtS5c3vSAPY",
    },
  ],
  "Ilaiyaraaja Magic": [
    {
      id: "keeravani-ragamulo-anveshana",
      title: "Keeravani Ragamulo",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Anveshana",
      year: 1985,
      duration: 280,
      videoId: "e9FeWDVqRpQ",
    },
    {
      id: "lalitha-priya-kamalam-rudraveena",
      title: "Lalitha Priya Kamalam",
      artist: "K. J. Yesudas, K. S. Chithra",
      film: "Rudra Veena",
      year: 1988,
      duration: 320,
      videoId: "-s3cdlJFhes",
    },
    {
      id: "nammaku-nammaku-rudraveena",
      title: "Nammaku Nammaku",
      artist: "S. P. Balasubrahmanyam",
      film: "Rudra Veena",
      year: 1988,
      duration: 295,
      videoId: "S8ANsRfVPSw",
    },
    {
      id: "mounamelanoyi-sagara-sangamam",
      title: "Mounamelanoyi Ee Marapurani Reyi",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Sagara Sangamam",
      year: 1983,
      duration: 310,
      videoId: "_JadUSYMufo",
    },
    {
      id: "botany-pathamundi-shiva",
      title: "Botany Pathamundi",
      artist: "S. P. Balasubrahmanyam",
      film: "Shiva",
      year: 1989,
      duration: 260,
      videoId: "g6LKzxOhTqQ",
    },
  ],
  "Terrace Nights": [
    {
      id: "bangaru-kodipetta-gharana-mogudu",
      title: "Bangaru Kodipetta",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Gharana Mogudu",
      year: 1992,
      duration: 244,
      videoId: "hxvUiz6s4Gk",
    },
    {
      id: "atho-athamma-kuthuro-alluda-mazaka",
      title: "Atho Athamma Kuthuro",
      artist: "S. P. Balasubrahmanyam",
      film: "Alluda Mazaka",
      year: 1995,
      duration: 265,
      videoId: "Hq-9Do_bSnw",
    },
    {
      id: "vaana-vaana-velluvaye-gang-leader",
      title: "Vaana Vaana Velluvaye",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Gang Leader",
      year: 1991,
      duration: 290,
      videoId: "pF-cNEi3oJw",
    },
    {
      id: "chik-chik-chelam-gang-leader",
      title: "Chik Chik Chelam",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Gang Leader",
      year: 1991,
      duration: 275,
      videoId: "lpfIHIjaLwg",
    },
    {
      id: "abbanee-tiyyani-jvas",
      title: "Abbanee Tiyyani Debba",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Jagadeka Veerudu Atiloka Sundari",
      year: 1990,
      duration: 320,
      videoId: "zloL0fdu5aM",
    },
    {
      id: "guvva-gorinka-tho-khaidi-786",
      title: "Guvva Gorinka Tho",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Khaidi No. 786",
      year: 1988,
      duration: 285,
      videoId: "gW_L9EDh2C4",
    },
    {
      id: "chiluka-kshemama-rowdy-alludu",
      title: "Chiluka Kshemama",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Rowdy Alludu",
      year: 1991,
      duration: 290,
      videoId: "vJgrRj-LYmM",
    },
    {
      id: "subhalekha-rasukunna-kondaveeti-donga",
      title: "Subhalekha Rasukunna",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Kondaveeti Donga",
      year: 1990,
      duration: 285,
      videoId: "0MRiY82zlnQ",
    },
  ],
};
