export type Track = {
  id: string;
  title: string;
  artist: string;
  film: string;
  year: number;
  duration: number;
  videoId: string;
};

// Embeddable YouTube tracks for Telugu Radio & OSTs
export const playlists: Record<string, Track[]> = {
  "Dude (Telugu)": [
    {
      id: "singari-dude-telugu",
      title: "Singari (Telugu)",
      artist: "Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 230,
      videoId: "cM-N8xT114E",
    },
    {
      id: "baagundu-po-dude",
      title: "Baagundu Po",
      artist: "Sanjith Hegde, Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 245,
      videoId: "sOaKk3XmX9M",
    },
    {
      id: "nee-gunde-lona-dude",
      title: "Nee Gunde Lona",
      artist: "Sai Abhyankkar, Jonita Gandhi",
      film: "Dude",
      year: 2025,
      duration: 220,
      videoId: "CqHjS-S8_qI",
    },
    {
      id: "boom-boom-dude-telugu",
      title: "Boom Boom (Telugu)",
      artist: "Sai Abhyankkar, Deepthi Suresh, bebhumika",
      film: "Dude",
      year: 2025,
      duration: 195,
      videoId: "5JoPeWHkKJg",
    },
    {
      id: "dude-telugu-jukebox",
      title: "Dude (Telugu Official Jukebox)",
      artist: "Sai Abhyankkar",
      film: "Dude",
      year: 2025,
      duration: 680,
      videoId: "2Lp9g1Z9c3s",
    },
    {
      id: "oorum-blood-rage-rock",
      title: "Oorum Blood (Rage Rock OST)",
      artist: "Sai Abhyankkar",
      film: "Dude (Original Score)",
      year: 2025,
      duration: 160,
      videoId: "2expHBvjI0s",
    },
  ],
  "OM Chapter 1 (Telugu)": [
    {
      id: "alaakaa-loova-telugu",
      title: "Alaakaa Loova (Telugu)",
      artist: "Sai Abhyankkar, Chandrabose",
      film: "OM: Chapter 1 - Udhiram",
      year: 2026,
      duration: 230,
      videoId: "wRMnTDlXYrs",
    },
    {
      id: "the-wild-theme-om",
      title: "The Wild Theme (BGM OST)",
      artist: "Sai Abhyankkar",
      film: "OM: Chapter 1",
      year: 2026,
      duration: 180,
      videoId: "k5j4c_kHw-E",
    },
    {
      id: "alaakaa-loova-unplugged",
      title: "Alaakaa Loova (Unplugged)",
      artist: "Sai Abhyankkar",
      film: "OM: Chapter 1",
      year: 2026,
      duration: 210,
      videoId: "1n0gXG-F1hY",
    },
  ],
  "Dhurandhar 2": [
    {
      id: "wild-ride-dhurandhar",
      title: "Wild Ride",
      artist: "Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 210,
      videoId: "VCfrL292Gmk",
    },
    {
      id: "aari-aari-telugu-dhurandhar",
      title: "Aari Aari (Telugu Version)",
      artist: "Adithya RK, Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 220,
      videoId: "El9lOzNyPb4",
    },
    {
      id: "phir-se-dhurandhar",
      title: "Phir Se",
      artist: "Arijit Singh, Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 260,
      videoId: "e2-yAj_wthU",
    },
    {
      id: "jaan-se-guzarte-hain-dhurandhar",
      title: "Jaan Se Guzarte Hain",
      artist: "Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 245,
      videoId: "P15G5XA8si4",
    },
    {
      id: "main-aur-tu-dhurandhar",
      title: "Main Aur Tu",
      artist: "Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 230,
      videoId: "X1twu3ztkPU",
    },
    {
      id: "hum-pyaar-karne-wale-dhurandhar",
      title: "Hum Pyaar Karne Wale",
      artist: "Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 225,
      videoId: "JVbtS-Y_ckw",
    },
    {
      id: "dhurandhar-revenge-jukebox",
      title: "Dhurandhar: The Revenge (Full OST Jukebox)",
      artist: "Shashwat Sachdev",
      film: "Dhurandhar: The Revenge",
      year: 2026,
      duration: 720,
      videoId: "f3i58ShlZjk",
    },
  ],
  "Animal (Telugu Album)": [
    {
      id: "nanna-nuv-naa-pranam-animal",
      title: "Nanna Nuv Naa Pranam",
      artist: "Sonu Nigam, Harshavardhan Rameshwar",
      film: "Animal",
      year: 2023,
      duration: 245,
      videoId: "kYJqD9t9u8E",
    },
    {
      id: "ammayi-animal",
      title: "Ammaayi",
      artist: "Raghav Chaitanya, Pritam",
      film: "Animal",
      year: 2023,
      duration: 260,
      videoId: "kY6T-c9nS8c",
    },
    {
      id: "ney-veyrey-animal",
      title: "Ney Veyrey",
      artist: "Karthik, Shreyas Puranik",
      film: "Animal",
      year: 2023,
      duration: 250,
      videoId: "g0ghPuWqYR0",
    },
    {
      id: "evarevaro-animal",
      title: "Evarevaro",
      artist: "Vishal Mishra",
      film: "Animal",
      year: 2023,
      duration: 240,
      videoId: "uB7bB-40x8Q",
    },
    {
      id: "animal-telugu-jukebox",
      title: "Animal (Telugu Full Video Jukebox)",
      artist: "Sonu Nigam, Karthik, Vishal Mishra, Pritam",
      film: "Animal",
      year: 2023,
      duration: 1200,
      videoId: "m0q0Yk3l2_w",
    },
  ],
  "Karappu OST (Telugu)": [
    {
      id: "god-mode-karuppu",
      title: "God Mode",
      artist: "Sai Abhyankkar, Gana Muthu, Vishnu Edavan",
      film: "Karappu (Veerabhadrudu)",
      year: 2026,
      duration: 210,
      videoId: "kY3wO_jT22M",
    },
    {
      id: "verappa-karuppu",
      title: "Verappa (Extended OST)",
      artist: "Sai Abhyankkar",
      film: "Karappu (Veerabhadrudu)",
      year: 2026,
      duration: 200,
      videoId: "Ja7Yz0MPbwI",
    },
    {
      id: "naanga-naalu-peru-karuppu",
      title: "Naanga Naalu Peru",
      artist: "Silambarasan TR, Sai Abhyankkar",
      film: "Karappu (Veerabhadrudu)",
      year: 2026,
      duration: 230,
      videoId: "sdajTOjARNg",
    },
    {
      id: "karuppa-kooda-va",
      title: "Karuppa Kooda Va",
      artist: "Sai Abhyankkar",
      film: "Karappu (Veerabhadrudu)",
      year: 2026,
      duration: 215,
      videoId: "-hZIVX0iv9w",
    },
    {
      id: "raathu-raasan-karuppu",
      title: "Raathu Raasan",
      artist: "Sai Abhyankkar",
      film: "Karappu (Veerabhadrudu)",
      year: 2026,
      duration: 195,
      videoId: "jApMnFmv2ig",
    },
  ],
  "Aaya Sher & Vanamali Telugu": [
    {
      id: "aaya-sher-paradise",
      title: "Aaya Sher",
      artist: "Anirudh Ravichander, Addula Jangireddy, Arjun Chandy",
      film: "The Paradise",
      year: 2026,
      duration: 215,
      videoId: "El9lOzNyPb4",
    },
    {
      id: "vanamaali-aakasam",
      title: "Vanamaali",
      artist: "Jayashree, Gopi Sundar, Samrat",
      film: "Aakasam",
      year: 2022,
      duration: 220,
      videoId: "wXQoF7i4u0U",
    },
    {
      id: "chilipiga-orange",
      title: "Chilipiga",
      artist: "Karthik, Harris Jayaraj, Vanamali",
      film: "Orange",
      year: 2010,
      duration: 320,
      videoId: "kYJjZ8k8Y28",
    },
    {
      id: "nenu-nuvvantu-orange",
      title: "Nenu Nuvvantu",
      artist: "Naresh Iyer, Snigdha Chandra, Harris Jayaraj, Vanamali",
      film: "Orange",
      year: 2010,
      duration: 280,
      videoId: "nFyuG_SYtLA",
    },
    {
      id: "arare-arare-happy-days",
      title: "Arare Arare",
      artist: "Karthik, Mickey J Meyer, Vanamali",
      film: "Happy Days",
      year: 2007,
      duration: 290,
      videoId: "U3iCXy8iJF8",
    },
    {
      id: "o-my-friend-happy-days",
      title: "O My Friend",
      artist: "Karthik, Mickey J Meyer, Vanamali",
      film: "Happy Days",
      year: 2007,
      duration: 295,
      videoId: "R2jZp8uK3qg",
    },
    {
      id: "evare-premam",
      title: "Evare",
      artist: "Vijay Yesudas, Rajesh Murugesan, Vanamali",
      film: "Premam",
      year: 2016,
      duration: 310,
      videoId: "J_u2c0-M-jA",
    },
  ],
  "Orange (Full Album)": [
    {
      id: "chilipiga-orange",
      title: "Chilipiga",
      artist: "Karthik, Harris Jayaraj, Vanamali",
      film: "Orange",
      year: 2010,
      duration: 320,
      videoId: "kYJjZ8k8Y28",
    },
    {
      id: "nenu-nuvvantu-orange",
      title: "Nenu Nuvvantu",
      artist: "Naresh Iyer, Snigdha Chandra, Harris Jayaraj, Vanamali",
      film: "Orange",
      year: 2010,
      duration: 280,
      videoId: "nFyuG_SYtLA",
    },
    {
      id: "ola-olala-ala-orange",
      title: "Ola Olala Ala",
      artist: "Karunya, Ranina Reddy, Harris Jayaraj",
      film: "Orange",
      year: 2010,
      duration: 340,
      videoId: "9D7wL2w-s84",
    },
    {
      id: "rooba-rooba-orange",
      title: "Rooba Rooba",
      artist: "Shail Hada, Chinmayi, Harris Jayaraj",
      film: "Orange",
      year: 2010,
      duration: 310,
      videoId: "F3zWw4P41qU",
    },
    {
      id: "hello-rammante-orange",
      title: "Hello Rammante",
      artist: "Vijay Prakash, Devan Ekambaram, Harris Jayaraj",
      film: "Orange",
      year: 2010,
      duration: 285,
      videoId: "HOkSSnvKzOh",
    },
  ],
  "Arjun Reddy (Full Album)": [
    {
      id: "emitemitemo-arjun-reddy",
      title: "Emitemitemo",
      artist: "Alphons Joseph, Radhan",
      film: "Arjun Reddy",
      year: 2017,
      duration: 210,
      videoId: "kYJ5oQjW598",
    },
    {
      id: "madhurame-arjun-reddy",
      title: "Madhurame",
      artist: "Sameera Bharadwaj, Radhan",
      film: "Arjun Reddy",
      year: 2017,
      duration: 245,
      videoId: "1F_454Y2d8g",
    },
    {
      id: "telisiney-na-nuvvey-arjun-reddy",
      title: "Telisiney Na Nuvvey",
      artist: "Revanth, Radhan",
      film: "Arjun Reddy",
      year: 2017,
      duration: 250,
      videoId: "mZ6o53y9y-8",
    },
    {
      id: "gundelona-arjun-reddy",
      title: "Gundelona",
      artist: "Sowjanya, Radhan",
      film: "Arjun Reddy",
      year: 2017,
      duration: 235,
      videoId: "w2WqW_0VvG4",
    },
    {
      id: "oopiri-aaguthunnadhey-arjun-reddy",
      title: "Oopiri Aaguthunnadhey",
      artist: "Revanth, Radhan",
      film: "Arjun Reddy",
      year: 2017,
      duration: 240,
      videoId: "Fk_X23vR25w",
    },
    {
      id: "arjun-reddy-jukebox",
      title: "Arjun Reddy (Full Audio Jukebox)",
      artist: "Radhan, Alphons Joseph, Revanth",
      film: "Arjun Reddy",
      year: 2017,
      duration: 1280,
      videoId: "r0w5qM75f78",
    },
  ],
  "Pelli Choopulu & Modern Indie": [
    {
      id: "chinuku-taake-pelli-choopulu",
      title: "Chinuku Taake",
      artist: "Vivek Sagar, Anurag Kulkarni",
      film: "Pelli Choopulu",
      year: 2016,
      duration: 220,
      videoId: "LGQ-hkDfMaI",
    },
    {
      id: "merise-merise-pelli-choopulu",
      title: "Merise Merise",
      artist: "Haricharan, Pranavi, Vivek Sagar",
      film: "Pelli Choopulu",
      year: 2016,
      duration: 260,
      videoId: "hB9i84O-v54",
    },
    {
      id: "aagi-aagi-ee-nagaraniki-emaindi",
      title: "Aagi Aagi",
      artist: "Anurag Kulkarni, Manisha Eerabathini, Vivek Sagar",
      film: "Ee Nagaraniki Emaindi",
      year: 2018,
      duration: 245,
      videoId: "kYJm3uH6Wog",
    },
    {
      id: "kallolam-padi-padi-leche-manasu",
      title: "Kallolam",
      artist: "Anurag Kulkarni, Vishal Chandrashekhar",
      film: "Padi Padi Leche Manasu",
      year: 2018,
      duration: 230,
      videoId: "Xh0YyGvN918",
    },
    {
      id: "kayyala-chindhata-keedaa-cola",
      title: "Kayyala Chindhata",
      artist: "Hemachandra, Vivek Sagar",
      film: "Keedaa Cola",
      year: 2023,
      duration: 215,
      videoId: "sO7jJ656p_U",
    },
    {
      id: "pelli-choopulu-jukebox",
      title: "Pelli Choopulu (Full Audio Jukebox)",
      artist: "Vivek Sagar",
      film: "Pelli Choopulu",
      year: 2016,
      duration: 980,
      videoId: "RuvCIeutNPk",
    },
  ],
  "Sapta Sagaralu Dhaati (Telugu & Original)": [
    {
      id: "sapta-sagaralu-dhaati-title-telugu",
      title: "Sapta Sagaralu Dhaati (Title Track)",
      artist: "Karthik Chennoju, Charan Raj",
      film: "Sapta Sagaralu Dhaati (Side A)",
      year: 2023,
      duration: 245,
      videoId: "Kz-zM2M2T6M",
    },
    {
      id: "kadalini-sapta-sagaralu-dhaati",
      title: "Kadalini",
      artist: "Charan Raj",
      film: "Sapta Sagaralu Dhaati (Side A)",
      year: 2023,
      duration: 230,
      videoId: "H7-6yB7P-iY",
    },
    {
      id: "sapta-sagaralu-dhaati-side-b-title",
      title: "Sapta Sagaralu Dhaati (Side B Title)",
      artist: "Charan Raj",
      film: "Sapta Sagaralu Dhaati (Side B)",
      year: 2023,
      duration: 250,
      videoId: "F1WfG7u8gV4",
    },
    {
      id: "sapta-sagaradaache-ello-jukebox",
      title: "Sapta Sagaradaache Ello (Original Side A Jukebox)",
      artist: "Charan Raj",
      film: "Sapta Sagaradaache Ello",
      year: 2023,
      duration: 1120,
      videoId: "wXW82n1-p94",
    },
  ],
  "Telugu & ARR Sensations": [
    {
      id: "nuvvu-naatho-emannavo-disco-raja",
      title: "Nuvvu Naatho Emannavo",
      artist: "S. P. Balasubrahmanyam, Thaman S",
      film: "Disco Raja",
      year: 2020,
      duration: 275,
      videoId: "1b70j04w0Lg",
    },
    {
      id: "pavazha-malli-sai-abhyankkar",
      title: "Pavazha Malli",
      artist: "Sai Abhyankkar, Shruti Haasan",
      film: "Pavazha Malli Single",
      year: 2025,
      duration: 210,
      videoId: "b68HETiNO98",
    },
    {
      id: "vellipomaake-sss",
      title: "Vellipomaake",
      artist: "Sid Sriram, A. R. Rahman",
      film: "Saahasam Swaasaga Saagipo",
      year: 2016,
      duration: 260,
      videoId: "5-P_397_w4s",
    },
    {
      id: "ninnu-choose-anandamlo-gang-leader",
      title: "Ninnu Choose Anandamlo",
      artist: "Sid Sriram, Anirudh Ravichander",
      film: "Gang Leader",
      year: 2019,
      duration: 235,
      videoId: "Ue51YvV4T2o",
    },
    {
      id: "usure-poyene-villain",
      title: "Usure Poyene",
      artist: "Karthik, A. R. Rahman",
      film: "Villain (Raavanan)",
      year: 2010,
      duration: 290,
      videoId: "DQtw-P6Hzo0",
    },
    {
      id: "mallipoo-vtk",
      title: "Mallipoo (Malle Poovu)",
      artist: "Madhushree, A. R. Rahman",
      film: "The Life of Muthu (VTK)",
      year: 2022,
      duration: 245,
      videoId: "MrzkoLKpgLU",
    },
    {
      id: "chola-chola-telugu-ps1",
      title: "Chola Chola (Telugu)",
      artist: "Mano, Anurag Kulkarni, A. R. Rahman",
      film: "Ponniyin Selvan: Part 1",
      year: 2022,
      duration: 235,
      videoId: "s1G7Y0yXm1U",
    },
    {
      id: "ninnele-radhe-shyam",
      title: "Ninnele",
      artist: "Anurag Kulkarni, Shreya Ghoshal, Justin Prabhakaran",
      film: "Radhe Shyam",
      year: 2022,
      duration: 240,
      videoId: "JmKxNfX5Fyk",
    },
    {
      id: "bande-vikram-vedha",
      title: "Bande",
      artist: "Sivam, Sam C.S.",
      film: "Vikram Vedha",
      year: 2017,
      duration: 200,
      videoId: "wLLLRdz-lwE",
    },
  ],
  "Roja Radio": [
    {
      id: "naa-cheli-rojave",
      title: "Naa Cheli Rojave",
      artist: "S. P. Balasubrahmanyam, Sujatha Mohan",
      film: "Roja",
      year: 1992,
      duration: 292,
      videoId: "alm844msx6E",
    },
    {
      id: "paruvam-vanaga-roja",
      title: "Paruvam Vanaga",
      artist: "S. P. Balasubrahmanyam, Sujatha Mohan",
      film: "Roja",
      year: 1992,
      duration: 305,
      videoId: "AW5oraAriXc",
    },
    {
      id: "chinna-chinna-aasa-roja",
      title: "Chinni Chinni Aasa",
      artist: "Minmini",
      film: "Roja",
      year: 1992,
      duration: 295,
      videoId: "Wm5n8V4N5f0",
    },
    {
      id: "vinaraa-vinaraa-roja",
      title: "Vinaraa Vinaraa",
      artist: "Mano",
      film: "Roja",
      year: 1992,
      duration: 238,
      videoId: "OGRnRyRtT7Y",
    },
    {
      id: "kannanule-bombay",
      title: "Kannanule",
      artist: "Hariharan, Kavita Krishnamurthy",
      film: "Bombay",
      year: 1995,
      duration: 298,
      videoId: "p-1gysnu4MM",
    },
    {
      id: "urike-chilaka-bombay",
      title: "Urike Chilaka",
      artist: "Hariharan, K. S. Chithra",
      film: "Bombay",
      year: 1995,
      duration: 310,
      videoId: "4J5aQNqRu_A",
    },
    {
      id: "mustafa-mustafa-prema-desam",
      title: "Mustafa Mustafa",
      artist: "A. R. Rahman",
      film: "Prema Desam",
      year: 1996,
      duration: 360,
      videoId: "M791NkagYAM",
    },
    {
      id: "hello-doctor-prema-desam",
      title: "Hello Doctor",
      artist: "A. R. Rahman, Storms, Noel, Anupama",
      film: "Prema Desam",
      year: 1996,
      duration: 285,
      videoId: "wwXjRV4V-1U",
    },
    {
      id: "urvasi-urvasi-premikudu",
      title: "Urvasi Urvasi",
      artist: "A. R. Rahman, Suresh Peters",
      film: "Premikudu",
      year: 1994,
      duration: 340,
      videoId: "97uVDPOibYw",
    },
    {
      id: "mukkala-mukkabula-premikudu",
      title: "Mukkala Mukkabula",
      artist: "Mano, Swarnalatha",
      film: "Premikudu",
      year: 1994,
      duration: 320,
      videoId: "vaw0k8HiP9A",
    },
  ],
  "DC OST": [
    {
      id: "dc-raga-of-revenge",
      title: "Raga of Revenge",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 185,
      videoId: "El9lOzNyPb4",
    },
    {
      id: "dc-aint-nobody",
      title: "Ain't Nobody",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 205,
      videoId: "e2-yAj_wthU",
    },
    {
      id: "dc-bloody-band",
      title: "Bloody Band",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 210,
      videoId: "P15G5XA8si4",
    },
    {
      id: "dc-bum-baa-diga-diga",
      title: "Bum Baa Diga Diga",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 198,
      videoId: "X1twu3ztkPU",
    },
    {
      id: "dc-the-rose-instrumental",
      title: "The Rose (Instrumental OST)",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 175,
      videoId: "VCfrL292Gmk",
    },
    {
      id: "dc-unreleased-jukebox",
      title: "DC BGM Score & Bangers Jukebox",
      artist: "Anirudh Ravichander",
      film: "DC",
      year: 2026,
      duration: 540,
      videoId: "JVbtS-Y_ckw",
    },
    {
      id: "the-dark-knight-main-theme",
      title: "The Dark Knight (Main Theme)",
      artist: "Hans Zimmer",
      film: "The Dark Knight (DC)",
      year: 2008,
      duration: 460,
      videoId: "iGx5a1ifSDs",
    },
    {
      id: "the-batman-theme",
      title: "The Batman (Main Theme)",
      artist: "Michael Giacchino",
      film: "The Batman (DC)",
      year: 2022,
      duration: 410,
      videoId: "Cwcinb2OxUo",
    },
    {
      id: "man-of-steel-flight",
      title: "Flight (Man of Steel OST)",
      artist: "Hans Zimmer",
      film: "Man of Steel (DC)",
      year: 2013,
      duration: 250,
      videoId: "w4OdIOGBW2Q",
    },
  ],
  "Cassette Evenings": [
    {
      id: "oh-priya-priya-geetanjali",
      title: "Oh Priya Priya",
      artist: "S. P. Balasubrahmanyam",
      film: "Geetanjali",
      year: 1989,
      duration: 308,
      videoId: "Q1a02C68ZXg",
    },
    {
      id: "aamani-paadave-geetanjali",
      title: "Aamani Paadave",
      artist: "K. S. Chithra",
      film: "Geetanjali",
      year: 1989,
      duration: 272,
      videoId: "vyH7ow2C4Zw",
    },
    {
      id: "oh-papa-laali-geetanjali",
      title: "Oh Papa Laali",
      artist: "Mano",
      film: "Geetanjali",
      year: 1989,
      duration: 290,
      videoId: "XK3gue1uR3w",
    },
    {
      id: "ee-manase-tholiprema",
      title: "Ee Manase Se Se",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Tholiprema",
      year: 1998,
      duration: 330,
      videoId: "zed5SZ2EiY0",
    },
    {
      id: "yemaindo-yemo-tholiprema",
      title: "Yemaindo Yemo Ee Vela",
      artist: "S. P. Balasubrahmanyam",
      film: "Tholiprema",
      year: 1998,
      duration: 290,
      videoId: "resKdlxjCbY",
    },
    {
      id: "telusa-manasa-criminal",
      title: "Telusa Manasa",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Criminal",
      year: 1994,
      duration: 295,
      videoId: "X206ZLAcKcI",
    },
    {
      id: "yeto-vellipoyindi-ninne-pelladata",
      title: "Yeto Vellipoyindi Manasu",
      artist: "Rajesh Krishnan, K. S. Chithra",
      film: "Ninne Pelladata",
      year: 1996,
      duration: 280,
      videoId: "FvcoRTJK_J8",
    },
    {
      id: "priya-priyathama-killer",
      title: "Priya Priyathama",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Killer",
      year: 1992,
      duration: 312,
      videoId: "Cc-0Tlg3SX8",
    },
    {
      id: "priyatama-naa-hrudayama-prema",
      title: "Priyatama Naa Hrudayama",
      artist: "S. P. Balasubrahmanyam",
      film: "Prema",
      year: 1989,
      duration: 315,
      videoId: "JSKSjPrnXU4",
    },
    {
      id: "kannula-basalu-prema-katha",
      title: "Kannula Baasalu",
      artist: "S. P. Balasubrahmanyam",
      film: "Prema Katha",
      year: 1999,
      duration: 275,
      videoId: "IGHHlJiv1ns",
    },
    {
      id: "chilaka-ye-thodu-leka-subhalagnam",
      title: "Chilaka Ye Thodu Leka",
      artist: "S. P. Balasubrahmanyam",
      film: "Subhalagnam",
      year: 1994,
      duration: 285,
      videoId: "LtS5c3vSAPY",
    },
  ],
  "Ilaiyaraaja Magic": [
    {
      id: "keeravani-ragamulo-anveshana",
      title: "Keeravani Ragamulo",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Anveshana",
      year: 1985,
      duration: 280,
      videoId: "e9FeWDVqRpQ",
    },
    {
      id: "lalitha-priya-kamalam-rudraveena",
      title: "Lalitha Priya Kamalam",
      artist: "K. J. Yesudas, K. S. Chithra",
      film: "Rudra Veena",
      year: 1988,
      duration: 320,
      videoId: "-s3cdlJFhes",
    },
    {
      id: "nammaku-nammaku-rudraveena",
      title: "Nammaku Nammaku",
      artist: "S. P. Balasubrahmanyam",
      film: "Rudra Veena",
      year: 1988,
      duration: 295,
      videoId: "S8ANsRfVPSw",
    },
    {
      id: "mounamelanoyi-sagara-sangamam",
      title: "Mounamelanoyi Ee Marapurani Reyi",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Sagara Sangamam",
      year: 1983,
      duration: 310,
      videoId: "_JadUSYMufo",
    },
    {
      id: "botany-pathamundi-shiva",
      title: "Botany Pathamundi",
      artist: "S. P. Balasubrahmanyam",
      film: "Shiva",
      year: 1989,
      duration: 260,
      videoId: "g6LKzxOhTqQ",
    },
  ],
  "Terrace Nights": [
    {
      id: "bangaru-kodipetta-gharana-mogudu",
      title: "Bangaru Kodipetta",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Gharana Mogudu",
      year: 1992,
      duration: 244,
      videoId: "hxvUiz6s4Gk",
    },
    {
      id: "atho-athamma-kuthuro-alluda-mazaka",
      title: "Atho Athamma Kuthuro",
      artist: "S. P. Balasubrahmanyam",
      film: "Alluda Mazaka",
      year: 1995,
      duration: 265,
      videoId: "Hq-9Do_bSnw",
    },
    {
      id: "vaana-vaana-velluvaye-gang-leader",
      title: "Vaana Vaana Velluvaye",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Gang Leader",
      year: 1991,
      duration: 290,
      videoId: "pF-cNEi3oJw",
    },
    {
      id: "chik-chik-chelam-gang-leader",
      title: "Chik Chik Chelam",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Gang Leader",
      year: 1991,
      duration: 275,
      videoId: "lpfIHIjaLwg",
    },
    {
      id: "abbanee-tiyyani-jvas",
      title: "Abbanee Tiyyani Debba",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Jagadeka Veerudu Atiloka Sundari",
      year: 1990,
      duration: 320,
      videoId: "zloL0fdu5aM",
    },
    {
      id: "guvva-gorinka-tho-khaidi-786",
      title: "Guvva Gorinka Tho",
      artist: "S. P. Balasubrahmanyam, S. Janaki",
      film: "Khaidi No. 786",
      year: 1988,
      duration: 285,
      videoId: "gW_L9EDh2C4",
    },
    {
      id: "chiluka-kshemama-rowdy-alludu",
      title: "Chiluka Kshemama",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Rowdy Alludu",
      year: 1991,
      duration: 290,
      videoId: "vJgrRj-LYmM",
    },
    {
      id: "subhalekha-rasukunna-kondaveeti-donga",
      title: "Subhalekha Rasukunna",
      artist: "S. P. Balasubrahmanyam, K. S. Chithra",
      film: "Kondaveeti Donga",
      year: 1990,
      duration: 285,
      videoId: "0MRiY82zlnQ",
    },
  ],
};
